@echo off
color 0A
title Piratage en cours...
echo Initialisation...
ping localhost -n 2 >nul
echo Connexion au serveur...
ping localhost -n 2 >nul
echo Injection du payload...
ping localhost -n 2 >nul
:loop
echo %random%%random%%random%%random%%random%%random%%random%
goto loop